
//users
export const GET_USERS = 'GET_USERS';
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const GET_ALL_CATS = 'GET_ALL_CATS';
export const GET_ALL_CATS_SUCCESS = 'GET_ALL_CATS_SUCCESS';
export const GET_ALL_CATS_FAILED = 'GET_ALL_CATS_FAILED';